### ISSUE TITLE
array header missing from utils.h

### ISSUE THREAD

**Issue by dkanou** [roboception/rcdiscover#1]
I am getting the following compiling error:
**rcdiscover/rcdiscover/utils.h:67:6: error: ‘array’ in namespace ‘std’ does not name a template type std::array<std::string, n> split(const std::string& s, const char sep)**

Not sure if this is related to my C++11 compatibility, but by adding the **#include \<array\>** header in rcdiscover/src/rcdiscover/rcdiscover/utils.h solved the issue.

**Comment by schallerr** [comment]
Thanks for pointing this out. I fixed the issue in bc6c86e030e786e94b4bb074fa31624a3d77c760.
