### ISSUE TITLE
Package 'libwxgtk3.0-dev' has no installation candidate

### ISSUE THREAD

**Issue by DanBmh** [roboception/rcdiscover#11]
The recommended linux compilation step didn't work:

```bash
> sudo apt-get install cmake libwxgtk3.0-dev

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libwxgtk3.0-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libwxgtk3.0-dev' has no installation candidate
```

Tested on Ubuntu 20.04

Installation with the prebuilt packages succeeded, but required two additional dependencies:
`libwxbase3.0-0v5` and `libwxgtk3.0-gtk3-0v5`

**Comment by heikohimu** [comment]
The package name has changed on 20.04. It is called libwxgtk3.0-gtk3-dev. I will update the readme.

**Comment by reddy-1025** [comment]
Is the above package working on kali linux?
