### ISSUE TITLE
can't make the package

### ISSUE THREAD

**Issue by itsmedralpha** [roboception/rcdiscover#12]
`
F:\rc_d\rcdiscover-1.0.3>mingw32-make
`
`
[  5%] Building CXX object rcdiscover/CMakeFiles/rcdiscover_static.dir/deviceinfo.cc.obj
`
`
[ 11%] Building CXX object rcdiscover/CMakeFiles/rcdiscover_static.dir/discover.cc.obj
`
`
F:\rc_d\rcdiscover-1.0.3\rcdiscover\discover.cc: In lambda function:
`
`
F:\rc_d\rcdiscover-1.0.3\rcdiscover\discover.cc:140:24: error: conversion from 'long long unsigned int' to 'int' may change value [-
`
`
Werror=conversion]
`
`
  140 |         if (select(sock+1, &fds, NULL, NULL, &tv) > 0)
      |                    ~~~~^~
`
`
cc1plus.exe: all warnings being treated as errors
mingw32-make[2]: *** [rcdiscover\CMakeFiles\rcdiscover_static.dir\build.make:91: rcdiscover/CMakeFiles/rcdiscover_static.dir/discover.cc.obj] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:115: rcdiscover/CMakeFiles/rcdiscover_static.dir/all] Error 2
mingw32-make: *** [makefile:165: all] Error 2
`

**Comment by itsmedralpha** [comment]
![Screenshot (12)](https://user-images.githubusercontent.com/66861623/162906351-0eecf5a4-7345-4d47-8c34-b94b22c7b8e2.png)

**Comment by heikohimu** [comment]
Thanks for reporting the issue. Have you seen that we provide executables for Windows? If you still want to recompile it yourself, please use the current version (i.e. 1.1.1.). If you still have issues, please report version of mingw / gcc that you use and post the full output as text instead of a screenshot.

**Comment by Divya9Sasidharan** [comment]
@heikohimu @flixr  I am currently experiencing an issue while compiling my project on Windows using mingw32-make. The error logs are attached for your reference. I am using version 1.1.7 of the software and MinGW/GCC version 7.3.0.

I need to update some changes in the GUI and therefore require a successful recompilation. Could you please assist me in resolving this issue?
[log 1.txt](https://github.com/roboception/rcdiscover/files/15413171/log.1.txt)
