### ISSUE TITLE
Error Compiling on Windows

### ISSUE THREAD

**Issue by Divya9Sasidharan** [roboception/rcdiscover#14]
I am currently experiencing an issue while compiling my project on Windows using mingw32-make. The error logs are attached for your reference. I am using version 1.1.7 of the software and MinGW/GCC version 7.3.0.

I need to update some changes in the GUI and therefore require a successful recompilation. Could you please assist me in resolving this issue?
[log.1.txt](https://github.com/roboception/rcdiscover/files/15413262/log.1.txt)

**Comment by heikohimu** [comment]
In version 2.0.0, we have re-written the GUI part to remove wxWidgets in favor of FLTK, which is easier to handle in a self-contained executable on different platforms. The repository now contains the build_win.bat script that can be executed in the Visual Studio command prompt for compiling everything from scratch. It was successfully tested with version 2022. For Linux, there is now also an AppImage that allows running the rcdiscover-gui on any Linux system.

**Comment by heikohimu** [comment]
Solved.
