### ISSUE TITLE
static library for rcdiscovery-gui

### ISSUE THREAD

**Issue by Yumin-Sun-00** [roboception/rcdiscover#2]
I only used suo apt-get install libwxgtk3.0-dev and then compiled. It works.

Not very sure why you suggest to do it per git clone and compile.

**Comment by schallerr** [comment]
Thanks for your request. You are right, manually cloning and compiling WxWidgets is not required on Linux - it is necessary only for Windows users.

**Comment by flixr** [comment]
@waschbaer00 to be honest, I don't quite understand.... Is the README.md not clear enough?
It already states that under Linux/Debian you just need to install `libwxgtk3.0-dev` and then compile....

**Comment by Yumin-Sun-00** [comment]
Oh, yes, you are right. I always can not see the title when I reading README, I just read top down.
