### ISSUE TITLE
Wrong IP address format in "Open Web GUI" option

### ISSUE THREAD

**Issue by bllngr** [roboception/rcdiscover#4]
rcdiscover shows one rc_wizard with the IP address 172.16.44.146. Selecting "Open Web GUI" from its context menu opens the browser at http://02940384, which of course doesn't work.

Edit: Tested with rcdiscover v0.9.0.

**Comment by schallerr** [comment]
Thanks for your bug report. This issue is fixed with release [v0.9.2](https://github.com/roboception/rcdiscover/releases/tag/v0.9.2).
