### ISSUE TITLE
Improve pointclouds

### ISSUE THREAD

**Issue by aycameric** [roboception/rcdiscover#5]
Hi,
what is a good option to improve my point clouds? Mine have holes and are not complete in the sense of the three dimensions of an object. Is there something I can tune? Do I have to use the accumulator? I saw this video: https://www.youtube.com/watch?v=chJ0rs4Ozog.

Thank you in advance!
Best regards,

**Comment by flixr** [comment]
Please contact support for questions: https://roboception.com/en/support/

Closing this issue as it does not pertain to rcdiscover.
