### ISSUE TITLE
Discovery of Roboception camera error code 10065

### ISSUE THREAD

**Issue by veronikafuerhaupter** [roboception/rcdiscover#6]
Discovery tool cannot identify connected camera.

![image](https://user-images.githubusercontent.com/82376680/114863457-07974c80-9df0-11eb-8448-4da21dc1ba5b.png)

**Comment by flixr** [comment]
Hi Veronika,

can you please provide some more details:

- windows version
- rcdiscover version
- network setup
- output of `route print` in Windows command prompt (`cmd`)
